"""empty message

Revision ID: 5eb13325fa5b
Revises: f94bbb2d2ea4
Create Date: 2022-03-17 19:30:03.356686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb13325fa5b'
down_revision = 'f94bbb2d2ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'people', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    # ### end Alembic commands ###
