"""empty message

Revision ID: 68cfc2d68b2e
Revises: d10c823042ad
Create Date: 2022-03-19 21:11:30.185498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cfc2d68b2e'
down_revision = 'd10c823042ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'like', ['likes_id'], ['id'])
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'likes_id')
    # ### end Alembic commands ###
