"""empty message

Revision ID: 699d83454b35
Revises: f39fff40aae4
Create Date: 2022-03-21 05:37:02.268107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699d83454b35'
down_revision = 'f39fff40aae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
