"""empty message

Revision ID: 8e09e496ed25
Revises: 330b6005aa3c
Create Date: 2022-03-15 19:00:16.123726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e09e496ed25'
down_revision = '330b6005aa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('password', sa.String(length=120), nullable=False))
    op.drop_column('people', 'passsword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('passsword', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('people', 'password')
    # ### end Alembic commands ###
