"""empty message

Revision ID: 914804d0b788
Revises: 7c953b47e89d
Create Date: 2022-03-28 00:25:17.332933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914804d0b788'
down_revision = '7c953b47e89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
