"""empty message

Revision ID: d10c823042ad
Revises: 8e09e496ed25
Create Date: 2022-03-17 15:33:28.401542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10c823042ad'
down_revision = '8e09e496ed25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('people_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'place', 'people', ['people_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.drop_column('place', 'people_id')
    # ### end Alembic commands ###
