"""empty message

Revision ID: f94bbb2d2ea4
Revises: 85049c58e25b
Create Date: 2022-03-17 17:31:43.455003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94bbb2d2ea4'
down_revision = '85049c58e25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('people_username_key', 'people', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('people_username_key', 'people', ['username'])
    # ### end Alembic commands ###
